#!/bin/bash

for i in 1 2 3 4 5 6
do
	port=$(netstat -an 2>/dev/null| grep :2407 | wc -l);
	echo $port;
	if [ ${port} -lt 1 ]; then
		kill -9 `netstat -anp | grep :59000 | awk -F" " '{print $7}' | awk -F"/" '{print $1}'`;
	fi;
done;
	
rm -f $0